//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motorbike
    {
        public int MotorbikeId { get; set; }
        public string MotorbikeModeOfUse { get; set; }
        public string MotorbikeRegistration { get; set; }
        public double MotorbikeValue { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
